
services:
  - type: static
    name: thestok-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    # Esta seção garante que o React Router funcione corretamente (SPA)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_KEY
        sync: false # Você deve definir esta chave manualmente no dashboard do Render
